////////////////////////////////////////////////////////////////////
// This file is automatically generated
// Do not edit manually
////////////////////////////////////////////////////////////////////

import React from 'react';
import ReactDOM from 'react-dom';

import { default as PlotlyExample } from '../reactopya_gallery/reactopya_gallery/PlotlyExample/PlotlyExample';
import { default as InteractivePlotlyExample } from '../reactopya_gallery/reactopya_gallery/InteractivePlotlyExample/InteractivePlotlyExample';
import { default as ElectrodeGeometry } from '../reactopya_gallery/reactopya_gallery/ElectrodeGeometry/ElectrodeGeometry';

var widgets = require('@jupyter-widgets/base');
var _ = require('lodash');

export class PlotlyExampleModel extends widgets.DOMWidgetModel {
    defaults = _.extend(widgets.DOMWidgetModel.prototype.defaults(), {
        _model_name : 'PlotlyExampleModel',
        _view_name : 'PlotlyExampleView',
        _model_module : 'reactopya_gallery_jupyter',
        _view_module : 'reactopya_gallery_jupyter',
        _model_module_version : '0.1.0',
        _view_module_version : '0.1.0',

        // Python state
        series: ''

        // JavaScript state
        

    })
}


// Custom View. Renders the widget model.
export class PlotlyExampleView extends widgets.DOMWidgetView {
    render() {
        this.div=document.createElement('div');
        this.el.appendChild(this.div);

        ReactDOM.render(
            <PlotlyExample jupyterModel={this.model} />,
            this.div
        );
    }
}

export class InteractivePlotlyExampleModel extends widgets.DOMWidgetModel {
    defaults = _.extend(widgets.DOMWidgetModel.prototype.defaults(), {
        _model_name : 'InteractivePlotlyExampleModel',
        _view_name : 'InteractivePlotlyExampleView',
        _model_module : 'reactopya_gallery_jupyter',
        _view_module : 'reactopya_gallery_jupyter',
        _model_module_version : '0.1.0',
        _view_module_version : '0.1.0',

        // Python state
        series: '',

        // JavaScript state
        noise_level: '',
        num_points: ''        

    })
}


// Custom View. Renders the widget model.
export class InteractivePlotlyExampleView extends widgets.DOMWidgetView {
    render() {
        this.div=document.createElement('div');
        this.el.appendChild(this.div);

        ReactDOM.render(
            <InteractivePlotlyExample jupyterModel={this.model} />,
            this.div
        );
    }
}

export class ElectrodeGeometryModel extends widgets.DOMWidgetModel {
    defaults = _.extend(widgets.DOMWidgetModel.prototype.defaults(), {
        _model_name : 'ElectrodeGeometryModel',
        _view_name : 'ElectrodeGeometryView',
        _model_module : 'reactopya_gallery_jupyter',
        _view_module : 'reactopya_gallery_jupyter',
        _model_module_version : '0.1.0',
        _view_module_version : '0.1.0',

        // Python state
        locations: '',
        labels: '',
        status: '',
        status_message: '',

        // JavaScript state
        path: '',
        download_from: ''        

    })
}


// Custom View. Renders the widget model.
export class ElectrodeGeometryView extends widgets.DOMWidgetView {
    render() {
        this.div=document.createElement('div');
        this.el.appendChild(this.div);

        ReactDOM.render(
            <ElectrodeGeometry jupyterModel={this.model} />,
            this.div
        );
    }
}
