####################################################################
## This file is automatically generated
## Do not edit manually
####################################################################

import ipywidgets as widgets
from traitlets import Unicode, Dict
import json

{imports}

def _json_parse(x):
    try:
        return json.loads(x)
    except:
        return None

def _json_stringify(x):
    try:
        return json.dumps(x)
    except:
        return ''

{widget_classes}